import type{Creator,Live,NewInRadarProduct,Product,SnapshotPeriod,Video}from '@/types';import type{ProductDataProvider}from './product-data-provider';import{calculateOpportunityScore,classifyOpportunity}from '@/lib/scoring/opportunity-score';import{calculateSaturationScore,classifySaturation}from '@/lib/scoring/saturation-score';import{calculateEstimatedSales}from '@/lib/scoring/estimated-sales';import{classifyGmvTier}from '@/lib/scoring/new-in-radar';
const cats=['Beleza','Casa','Eletrônicos','Moda','Acessórios','Saúde e bem-estar','Automotivo','Ferramentas','Esportes','Pets'];const names=['Mini seladora portátil','Luminária touch sem fio','Sérum reparador premium','Escova secadora 5 em 1','Organizador modular','Fone bluetooth compacto','Kit faixa elástica','Garrafa térmica inox','Limpador multifuncional','Cama nuvem para pets','Suporte magnético veicular','Modelador de cachos automático'];const shops=Array.from({length:30},(_,i)=>({id:`s${i+1}`,name:['Pratic Shop','Viva Lar','Beleza Lab','Tech Agora','Mundo Pet'][i%5]+` ${i+1}`,category:cats[i%10],activeProducts:18+i%34,sales:1900+i*317,gmv:120000+i*18750,growth:i%5===0?184:22+i%67,rating:4.5+(i%5)/10,creators:12+i%88}));
const products:Product[]=Array.from({length:100},(_,i)=>{const growth=[387,264,218,-40,8,146,92][i%7],price=29.9+(i%12)*10,creators=12+(i*7)%130,videos=30+(i*13)%300,sales=120+(i*83)%1800;const sat=calculateSaturationScore({creators,videos,sellers:1+i%9,sales,newCreatorGrowth:8+i%45});const score=Math.max(30,Math.min(99,calculateOpportunityScore({salesAcceleration:Math.max(0,Math.min(100,growth/4)),gmvGrowth:Math.max(0,60+growth/8),creatorGrowth:55+i%45,videoGrowth:40+i%55,commission:8+i%13,competition:sat,price})));return{id:`p${i+1}`,name:`${names[i%names.length]}${i>=12?` · ${i+1}`:''}`,shop:shops[i%30].name,category:cats[i%10],price,originalPrice:i%3===0?price*1.24:undefined,sales24h:sales,sales7d:sales*5+i*47,gmv:sales*price*5,estimatedSales:calculateEstimatedSales(sales*price*5,price),growth24h:growth,growth7d:growth*.72,growth30d:growth*.39,creators,newCreators:4+i%38,videos,newVideos:7+i%59,views:170000+i*93417,commission:8+i%13,rating:4.3+(i%7)/10,reviews:230+i*71,opportunityScore:score,opportunityFactors:[],saturation:classifySaturation(sat),status:classifyOpportunity(score),rankingVelocity:Math.round(4+i%18),momentum:growth>100?Math.round(12+i%22):growth<0?-18:2,trend:growth>100?'Acelerando':growth<0?'Em queda':'Estável',rankingHistory:Array.from({length:7},(_,d)=>({date:'Dia '+(d+1),ranking:Math.max(1,92-d*(8+i%7))})),history:Array.from({length:14},(_,d)=>({date:`${d+11} ago`,sales:Math.round(sales*(.35+d*.055)*(growth>100?1+d*.045:1)),gmv:Math.round(sales*price*(.35+d*.055)),creators:Math.round(creators*.55+d*2),videos:Math.round(videos*.42+d*5)}))}});
const creators:Creator[]=Array.from({length:100},(_,i)=>{const gmv=87000+i*15900;return{id:`c${i+1}`,name:['Marina Alves','Lucas Prado','Bia Recomenda','Achadinhos da Ju','Rafa Testou'][i%5]+` ${i+1}`,username:`@radar${i+1}`,imageUrl:undefined,ranking:i+1,period:'7D',followers:43000+i*9107,sales:1300+i*147,gmv,gmvRangeMin:Math.round(gmv*0.85),gmvRangeMax:Math.round(gmv*1.15),products:3+i%22,videos:12+i%76,views:590000+i*133000,engagement:3.2+(i%18)/10,growth:8+i%95}});const videos:Video[]=Array.from({length:300},(_,i)=>({id:`v${i+1}`,creator:creators[i%100].name,product:products[i%100].name,views:33000+i*8541,likes:2800+i*317,comments:190+i*21,shares:80+i*17,sales:45+i%870,gmv:(45+i%870)*(products[i%100].price??0),date:`${1+i%28} ago`,growth:-12+i%240,url:'https://www.tiktok.com/'}));
const lives:Live[]=Array.from({length:20},(_,i)=>({id:`l${i+1}`,name:`Live de ${products[i%100].name}`,gmv:38000+i*4300,ranking:i+1}));

// "Novos no radar" em modo demonstrativo: reaproveita os mesmos 16 primeiros
// produtos fictícios (mesma disciplina do resto do mock — nada novo é
// inventado além do que os outros mocks já fabricam) e aplica exatamente a
// mesma regra de faixas (classifyGmvTier) usada com dados reais. Produtos
// cujo GMV demonstrativo não alcança R$ 10 mil ficam de fora, como aconteceria
// com dados reais.
const newInRadar:NewInRadarProduct[]=products.slice(0,16).flatMap((p,i):NewInRadarProduct[]=>{
  const rangeMin=Math.round(((p.gmv??0)*0.85)/100)*100,rangeMax=Math.round(((p.gmv??0)*1.15)/100)*100;
  const tier=classifyGmvTier(rangeMin);
  if(tier===null)return[];
  const hist=p.rankingHistory;
  const latestRanking=hist[hist.length-1]?.ranking??1;
  const previousRanking=hist.length>=2?hist[hist.length-2].ranking:null;
  const firstDetectedAt=new Date(Date.now()-(i%7)*86400000).toISOString();
  return[{id:p.id,name:p.name,shop:p.shop,imageUrl:p.imageUrl,productUrl:p.productUrl,gmvRangeMin:rangeMin,gmvRangeMax:rangeMax,gmvTier:tier,firstDetectedAt,ranking:latestRanking,price:null,soldCount:null,commission:null,creators:null,previousRanking,gmvGrowthPct:p.growth7d,hasConfirmedGrowth:previousRanking!==null&&(latestRanking<previousRanking||(p.growth7d??0)>0),snapshotsCount:hist.length}];
});

export class MockTikTokProvider implements ProductDataProvider{async getProducts(){return products}async getProduct(id:string){return products.find(p=>p.id===id)??null}async getProductMetrics(id:string){return (await this.getProduct(id))?.history??[]}async getCreators(period:SnapshotPeriod='7D'){return creators.map(c=>({...c,period}))}async getShops(){return shops}async getVideos(){return videos}async getLives(){return lives}async getNewInRadar(){return newInRadar}}
export const dataProvider:ProductDataProvider=new MockTikTokProvider();
