'use client';

import { BarChart3, Bell, Box, ChevronDown, CircleHelp, Compass, LayoutDashboard, Menu, Search, Sparkles, Store, Users, Video } from 'lucide-react';
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';

const menu = [[LayoutDashboard,'Visão geral'],[Box,'Produtos'],[Compass,'Radar de oportunidades'],[Users,'Criadores'],[Store,'Lojas'],[Video,'Vídeos'],[BarChart3,'Categorias']] as const;
const stats = [['GMV analisado','R$ 18,4 mi','+18,2%'],['Vendas analisadas','284,7 mil','+12,4%'],['Produtos monitorados','12.842','+384'],['Oportunidades detectadas','148','+21 hoje']];
const chart = [{d:'18 ago',gmv:1.2},{d:'19 ago',gmv:1.55},{d:'20 ago',gmv:1.43},{d:'21 ago',gmv:1.86},{d:'22 ago',gmv:2.04},{d:'23 ago',gmv:2.42},{d:'24 ago',gmv:2.78}];
const products = [['MS','Mini seladora portátil','Casa','R$ 49,90','842','+387%','96'],['LE','Luminária elegante touch','Casa','R$ 79,90','679','+264%','92'],['SR','Sérum reparador premium','Beleza','R$ 62,50','591','+218%','89']];

export default function Home(){return <main className="app-shell">
  <aside className="sidebar"><div className="brand"><span className="brand-mark"><Sparkles size={17}/></span><span>TikRadar</span></div><p className="eyebrow">INTELIGÊNCIA</p><nav>{menu.map(([Icon,label],i)=><button className={i===0?'nav-item active':'nav-item'} key={label}><Icon size={18}/><span>{label}</span>{i===2&&<b>12</b>}</button>)}</nav><div className="sidebar-foot"><button className="nav-item"><CircleHelp size={18}/>Central de ajuda</button><div className="user"><span>AG</span><div><strong>Adriel Godoy</strong><small>Plano Pro</small></div><ChevronDown size={15}/></div></div></aside>
  <section className="content"><header className="topbar"><button className="mobile-menu"><Menu/></button><div className="search"><Search size={17}/><span>Buscar produtos, lojas ou criadores...</span><kbd>⌘ K</kbd></div><button className="icon-button"><Bell size={18}/><i/></button><span className="live"><i/> Dados atualizados</span></header>
  <div className="page"><div className="title-row"><div><p className="eyebrow green">VISÃO GERAL</p><h1>Bom dia, Adriel.</h1><p>Veja o que está movimentando o TikTok Shop hoje.</p></div><div className="filters"><button>Brasil <ChevronDown size={14}/></button><button>Últimos 7 dias <ChevronDown size={14}/></button></div></div>
  <div className="stats">{stats.map((s,i)=><article key={s[0]}><div className={'stat-icon i'+i}>{i===0?<BarChart3/>:i===1?<Sparkles/>:i===2?<Box/>:<Compass/>}</div><p>{s[0]}</p><div><strong>{s[1]}</strong><span>{s[2]}</span></div></article>)}</div>
  <div className="main-grid"><article className="panel chart-panel"><div className="panel-head"><div><h2>GMV ao longo do tempo</h2><p>Volume bruto de mercadorias analisado</p></div><span className="trend">↗ 18,2%</span></div><div className="chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={chart}><defs><linearGradient id="fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#167b58" stopOpacity={.2}/><stop offset="100%" stopColor="#167b58" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="#edf0ee" vertical={false}/><XAxis dataKey="d" axisLine={false} tickLine={false}/><YAxis axisLine={false} tickLine={false} tickFormatter={v=>`R$ ${v}m`}/><Tooltip formatter={(v)=>[`R$ ${v} mi`,'GMV']}/><Area type="monotone" dataKey="gmv" stroke="#167b58" strokeWidth={2.5} fill="url(#fill)"/></AreaChart></ResponsiveContainer></div></article>
  <article className="panel radar-card"><div className="panel-head"><div><p className="eyebrow green">RADAR</p><h2>Sinais de oportunidade</h2></div><span className="pulse"><i/> AO VIVO</span></div><strong className="big-number">21</strong><p>novos produtos promissores detectados hoje</p><div className="radar-lines"><span style={{width:'88%'}}/><span style={{width:'62%'}}/><span style={{width:'76%'}}/></div><button>Explorar Radar <span>→</span></button></article></div>
  <article className="panel table-panel"><div className="panel-head"><div><h2>Produtos em maior crescimento</h2><p>Itens com aceleração relevante e saturação controlada</p></div><button className="link">Ver todos →</button></div><div className="table-wrap"><table><thead><tr><th>PRODUTO</th><th>CATEGORIA</th><th>PREÇO</th><th>VENDAS 24H</th><th>CRESCIMENTO</th><th>OPORTUNIDADE</th></tr></thead><tbody>{products.map((p,i)=><tr key={p[1]}><td><span className={'product-img p'+i}>{p[0]}</span><div><strong>{p[1]}</strong><small>{i===0?'Pratic Shop':'Loja verificada'}</small></div></td><td><span className="tag">{p[2]}</span></td><td>{p[3]}</td><td><strong>{p[4]}</strong></td><td><span className="growth">↗ {p[5]}</span></td><td><span className="score">{p[6]}</span><div className="score-text"><strong>{i<2?'Forte oportunidade':'Tendência'}</strong><small>Saturação baixa</small></div></td></tr>)}</tbody></table></div></article>
  </div></section></main>}
