import{z}from'zod';import type{TikTokConfig}from'./config';import type{TikTokOAuthTokens}from'./types';import{TikTokAuthError,TikTokConfigError}from'./errors';import{generateTikTokSignature}from'./signature';
const responseSchema=z.object({code:z.number(),message:z.string(),request_id:z.string().optional(),data:z.object({access_token:z.string(),access_token_expire_in:z.number(),refresh_token:z.string(),refresh_token_expire_in:z.number(),open_id:z.string(),seller_name:z.string().optional(),seller_base_region:z.string().optional(),user_type:z.number(),granted_scopes:z.array(z.string()).optional()})});
export function createSellerAuthorizationUrl(config:TikTokConfig,state:string){if(!config.serviceId)throw new TikTokConfigError('TIKTOK_SHOP_SERVICE_ID não configurado.');const url=new URL(config.authorizeUrl);url.searchParams.set('service_id',config.serviceId);url.searchParams.set('state',state);return url.toString()}
async function tokenRequest(config:TikTokConfig,path:string,params:Record<string,string>){if(!config.appKey||!config.appSecret)throw new TikTokConfigError('App Key ou App Secret não configurados.');const url=new URL(path,config.authBaseUrl);for(const[k,v]of Object.entries({app_key:config.appKey,app_secret:config.appSecret,...params}))url.searchParams.set(k,v);const response=await fetch(url,{method:'GET',headers:{accept:'application/json'},cache:'no-store'});const parsed=responseSchema.safeParse(await response.json());if(!response.ok||!parsed.success||parsed.data.code!==0)throw new TikTokAuthError(parsed.success?`TikTok OAuth: ${parsed.data.message}`:'Resposta OAuth inválida.');const d=parsed.data.data;return{accessToken:d.access_token,accessTokenExpiresAt:d.access_token_expire_in,refreshToken:d.refresh_token,refreshTokenExpiresAt:d.refresh_token_expire_in,openId:d.open_id,sellerName:d.seller_name,sellerBaseRegion:d.seller_base_region,userType:d.user_type,grantedScopes:d.granted_scopes??[]}satisfies TikTokOAuthTokens}
export const exchangeAuthorizationCode=(config:TikTokConfig,code:string)=>tokenRequest(config,'/api/v2/token/get',{auth_code:code,grant_type:'authorized_code'});
export const refreshSellerToken=(config:TikTokConfig,refreshToken:string)=>tokenRequest(config,'/api/v2/token/refresh',{refresh_token:refreshToken,grant_type:'refresh_token'});

const shopsSchema=z.object({code:z.coerce.number(),message:z.string().nullish(),request_id:z.string().optional(),data:z.object({shops:z.array(z.object({cipher:z.string().optional(),shop_cipher:z.string().optional(),name:z.string().optional(),shop_name:z.string().optional(),region:z.string().optional(),region_code:z.string().optional()}))})});
export async function getAuthorizedShop(config:TikTokConfig,accessToken:string){if(!config.appKey||!config.appSecret)throw new TikTokConfigError('App Key ou App Secret não configurados.');const path='/authorization/202309/shops',timestamp=Math.floor(Date.now()/1000),query={app_key:config.appKey,timestamp};const sign=await generateTikTokSignature({path,query,appSecret:config.appSecret});const url=new URL(path,config.apiBaseUrl);for(const[k,v]of Object.entries({...query,sign}))url.searchParams.set(k,String(v));const response=await fetch(url,{headers:{accept:'application/json','content-type':'application/json','x-tts-access-token':accessToken},cache:'no-store'});const payload=await response.json().catch(()=>null),parsed=shopsSchema.safeParse(payload);if(!response.ok||!parsed.success)throw new TikTokAuthError(`Resposta inválida ao consultar a loja autorizada (HTTP ${response.status}).`);if(parsed.data.code!==0)throw new TikTokAuthError(`TikTok Shops: ${parsed.data.message??`código ${parsed.data.code}`}`);const raw=parsed.data.data.shops[0],cipher=raw?.cipher??raw?.shop_cipher;if(!raw||!cipher)throw new TikTokAuthError('Nenhuma loja autorizada foi encontrada.');return{cipher,name:raw.name??raw.shop_name,region:raw.region??raw.region_code}}
