import{createClient}from'@supabase/supabase-js';
import type{TikTokOAuthTokens}from'./types';
import{TikTokConfigError}from'./errors';
function decodeKey(value:string){const raw=Uint8Array.from(atob(value),c=>c.charCodeAt(0));if(raw.length!==32)throw new TikTokConfigError('TIKTOK_TOKEN_ENCRYPTION_KEY deve conter 32 bytes em Base64.');return raw}
async function cryptoKey(value:string,usage:KeyUsage){return crypto.subtle.importKey('raw',decodeKey(value),{name:'AES-GCM'},false,[usage])}
async function encrypt(value:string,keyValue:string){const iv=crypto.getRandomValues(new Uint8Array(12)),key=await cryptoKey(keyValue,'encrypt'),cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,new TextEncoder().encode(value));const joined=new Uint8Array(iv.length+cipher.byteLength);joined.set(iv);joined.set(new Uint8Array(cipher),iv.length);return btoa(String.fromCharCode(...joined))}
async function decrypt(value:string,keyValue:string){const joined=Uint8Array.from(atob(value),c=>c.charCodeAt(0)),iv=joined.slice(0,12),cipher=joined.slice(12),key=await cryptoKey(keyValue,'decrypt');return new TextDecoder().decode(await crypto.subtle.decrypt({name:'AES-GCM',iv},key,cipher))}
export class SupabaseTikTokTokenStore{
  constructor(private env:NodeJS.ProcessEnv=process.env){}
  private client(){const url=this.env.NEXT_PUBLIC_SUPABASE_URL,role=this.env.SUPABASE_SECRET_KEY??this.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!role)throw new TikTokConfigError('Token store seguro não configurado.');return createClient(url,role,{auth:{persistSession:false}})}
  private key(){const key=this.env.TIKTOK_TOKEN_ENCRYPTION_KEY;if(!key)throw new TikTokConfigError('Token store seguro não configurado.');return key}
  async save(tokens:TikTokOAuthTokens,userId?:string){const key=this.key(),client=this.client(),row={platform_user_id:userId||null,open_id:tokens.openId,seller_name:tokens.sellerName,seller_base_region:tokens.sellerBaseRegion,shop_cipher:tokens.shopCipher,access_token_ciphertext:await encrypt(tokens.accessToken,key),refresh_token_ciphertext:await encrypt(tokens.refreshToken,key),access_token_expires_at:new Date(tokens.accessTokenExpiresAt*1000).toISOString(),refresh_token_expires_at:new Date(tokens.refreshTokenExpiresAt*1000).toISOString(),granted_scopes:tokens.grantedScopes,updated_at:new Date().toISOString()};const{error}=await client.from('tiktok_connections').upsert(row,{onConflict:'platform_user_id,open_id'});if(error)throw new TikTokConfigError(`Falha ao salvar conexão: ${error.message}`);const{error:auditError}=await client.from('security_audit_events').insert({platform_user_id:userId||null,event_type:'tiktok_connection_saved',metadata:{open_id_suffix:tokens.openId.slice(-6)}});if(auditError)throw new TikTokConfigError(`Conexão salva, mas a auditoria falhou: ${auditError.message}`)}
  async latest(userId?:string){const key=this.key();let query=this.client().from('tiktok_connections').select('open_id,seller_name,seller_base_region,shop_cipher,access_token_ciphertext,refresh_token_ciphertext,access_token_expires_at,refresh_token_expires_at,granted_scopes,updated_at').order('updated_at',{ascending:false}).limit(1);if(userId)query=query.eq('platform_user_id',userId);const{data,error}=await query.maybeSingle();if(error)throw new TikTokConfigError(`Falha ao ler conexão: ${error.message}`);if(!data)return null;return{openId:data.open_id,sellerName:data.seller_name??undefined,sellerBaseRegion:data.seller_base_region??undefined,shopCipher:data.shop_cipher??undefined,accessToken:await decrypt(data.access_token_ciphertext,key),refreshToken:await decrypt(data.refresh_token_ciphertext,key),accessTokenExpiresAt:new Date(data.access_token_expires_at).getTime()/1000,refreshTokenExpiresAt:new Date(data.refresh_token_expires_at).getTime()/1000,userType:0,grantedScopes:data.granted_scopes??[],updatedAt:data.updated_at}}
  async status(userId:string){const{data,error}=await this.client().from('tiktok_connections').select('seller_name,seller_base_region,shop_cipher,access_token_expires_at,granted_scopes,updated_at').eq('platform_user_id',userId).order('updated_at',{ascending:false}).limit(1).maybeSingle();if(error)throw new TikTokConfigError(`Falha ao consultar conexão: ${error.message}`);return data}
  async deleteForUser(userId:string){const client=this.client();const{error,count}=await client.from('tiktok_connections').delete({count:'exact'}).eq('platform_user_id',userId);if(error)throw error;await client.from('security_audit_events').insert({platform_user_id:userId,event_type:'tiktok_connection_deleted',metadata:{deleted_connections:count??0}});return count??0}
}
