import{createClient}from'@supabase/supabase-js';
import type{TikTokOAuthTokens}from'./types';
import{TikTokConfigError}from'./errors';
function decodeKey(value:string){const raw=Uint8Array.from(atob(value),c=>c.charCodeAt(0));if(raw.length!==32)throw new TikTokConfigError('TIKTOK_TOKEN_ENCRYPTION_KEY deve conter 32 bytes em Base64.');return raw}
async function encrypt(value:string,keyValue:string){const iv=crypto.getRandomValues(new Uint8Array(12)),key=await crypto.subtle.importKey('raw',decodeKey(keyValue),{name:'AES-GCM'},false,['encrypt']);const cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,new TextEncoder().encode(value));const joined=new Uint8Array(iv.length+cipher.byteLength);joined.set(iv);joined.set(new Uint8Array(cipher),iv.length);return btoa(String.fromCharCode(...joined))}
export class SupabaseTikTokTokenStore{
  constructor(private env:NodeJS.ProcessEnv=process.env){}
  private client(){const url=this.env.NEXT_PUBLIC_SUPABASE_URL,role=this.env.SUPABASE_SECRET_KEY??this.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!role)throw new TikTokConfigError('Token store seguro não configurado.');return createClient(url,role,{auth:{persistSession:false}})}
  async save(tokens:TikTokOAuthTokens,userId?:string){const key=this.env.TIKTOK_TOKEN_ENCRYPTION_KEY;if(!key)throw new TikTokConfigError('Token store seguro não configurado.');const client=this.client();const row={platform_user_id:userId||null,open_id:tokens.openId,seller_name:tokens.sellerName,seller_base_region:tokens.sellerBaseRegion,access_token_ciphertext:await encrypt(tokens.accessToken,key),refresh_token_ciphertext:await encrypt(tokens.refreshToken,key),access_token_expires_at:new Date(tokens.accessTokenExpiresAt*1000).toISOString(),refresh_token_expires_at:new Date(tokens.refreshTokenExpiresAt*1000).toISOString(),granted_scopes:tokens.grantedScopes,updated_at:new Date().toISOString()};const{error}=await client.from('tiktok_connections').upsert(row,{onConflict:'platform_user_id,open_id'});if(error)throw error;await client.from('security_audit_events').insert({platform_user_id:userId||null,event_type:'tiktok_connection_saved',metadata:{open_id_suffix:tokens.openId.slice(-6)}})}
  async deleteForUser(userId:string){const client=this.client();const{error,count}=await client.from('tiktok_connections').delete({count:'exact'}).eq('platform_user_id',userId);if(error)throw error;await client.from('security_audit_events').insert({platform_user_id:userId,event_type:'tiktok_connection_deleted',metadata:{deleted_connections:count??0}});return count??0}
}
