import{TikTokSchemaError}from'@/lib/tiktok/errors';import type{BestsellersKind,NormalizedBestseller,TikTokApiEnvelope,TikTokCurrency}from'@/lib/tiktok/types';
export interface BestsellersAdapter{normalize(kind:BestsellersKind,response:TikTokApiEnvelope<unknown>,currency:TikTokCurrency):NormalizedBestseller[]}
export class UnconfiguredBestsellersAdapter implements BestsellersAdapter{normalize():NormalizedBestseller[]{throw new TikTokSchemaError('Adapter Bestsellers ainda não configurado. Capture uma resposta oficial no API Testing Tool e implemente o mapeamento sem inferir campos.')}}
export function normalizeGmvRange(input:{min:unknown;max:unknown;display?:unknown;currency:TikTokCurrency}):import('@/lib/tiktok/types').GmvRange{const min=typeof input.min==='number'&&Number.isFinite(input.min)?input.min:null,max=typeof input.max==='number'&&Number.isFinite(input.max)?input.max:null;const estimated=min!==null&&max!==null?(min+max)/2:null;const display=typeof input.display==='string'&&input.display.trim()?input.display:min!==null&&max!==null?`${min.toLocaleString('pt-BR')} – ${max.toLocaleString('pt-BR')}`:'Faixa não informada';return{gmvMin:min,gmvMax:max,gmvEstimated:estimated,gmvDisplay:display,currency:input.currency,isExact:false}}

type JsonRecord=Record<string,unknown>;
const records=(value:unknown):JsonRecord[]=>Array.isArray(value)?value.filter((x):x is JsonRecord=>Boolean(x)&&typeof x==='object'):[];
const numberValue=(value:unknown)=>typeof value==='number'&&Number.isFinite(value)?value:typeof value==='string'&&value.trim()&&Number.isFinite(Number(value))?Number(value):undefined;
const stringValue=(...values:unknown[])=>values.find((value):value is string=>typeof value==='string'&&Boolean(value.trim()));
function rangeNumber(value:string){const cleaned=value.replace(/[^0-9.,KMB]/gi,'').replace(',','.');const match=cleaned.match(/([0-9.]+)\s*([KMB])?/i);if(!match)return null;const amount=Number(match[1]);if(!Number.isFinite(amount))return null;return amount*({K:1e3,M:1e6,B:1e9}[match[2]?.toUpperCase() as 'K'|'M'|'B']??1)}
function gmv(value:unknown,currency:TikTokCurrency){if(typeof value==='string'){const parts=value.split(/\s*[~–—-]\s*/).map(rangeNumber);return normalizeGmvRange({min:parts[0],max:parts[1]??parts[0],display:value,currency})}if(value&&typeof value==='object'){const r=value as JsonRecord;return normalizeGmvRange({min:numberValue(r.minimum_amount??r.min),max:numberValue(r.maximum_amount??r.max),currency,display:r.display})}return normalizeGmvRange({min:null,max:null,currency})}
function collection(data:unknown,kind:BestsellersKind){if(!data||typeof data!=='object')return[];return records((data as JsonRecord)[kind])}
export class TikTokBestsellersAdapter implements BestsellersAdapter{normalize(kind:BestsellersKind,response:TikTokApiEnvelope<unknown>,currency:TikTokCurrency){return collection(response.data,kind).map((item,index)=>{const products=records(item.product_infos),firstProduct=products[0];const externalId=stringValue(item.id,item.product_id,item.creator_id,item.video_id,item.live_id,item.room_id,item.open_id,item.username,kind==='videos'?`video:${item.publish_time??index}:${firstProduct?.product_id??index}`:undefined,kind==='lives'?`live:${item.start_time??item.publish_time??index}`:undefined);if(!externalId)throw new TikTokSchemaError(`Resposta Bestsellers sem identificador em ${kind}.`);return{externalId,ranking:numberValue(item.rank??item.ranking)??index+1,name:stringValue(item.name,item.product_name,item.nickname,item.username,item.title,firstProduct?.product_name),gmv:gmv(item.gmv_range??item.gmv,currency),soldCount:numberValue(item.sold_count??item.sales??item.units_sold),price:numberValue(item.price),creatorCount:numberValue(item.creator_count),videoCount:numberValue(item.video_count),reviewCount:numberValue(item.review_count),rating:numberValue(item.rating),creatorExternalId:stringValue(item.creator_id,item.open_id),productExternalId:stringValue(item.product_id,firstProduct?.product_id),views:numberValue(item.views??item.view_count),rawPayload:item} satisfies NormalizedBestseller})}}
